
package services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param id
     * @return
     *     returns services.Anagrafica
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserById", targetNamespace = "http://services/", className = "services.GetUserById")
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://services/", className = "services.GetUserByIdResponse")
    public Anagrafica getUserById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://services/", className = "services.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://services/", className = "services.DeleteUserResponse")
    public void deleteUser(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param anagrafica
     */
    @WebMethod
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://services/", className = "services.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://services/", className = "services.UpdateUserResponse")
    public void updateUser(
        @WebParam(name = "anagrafica", targetNamespace = "http://services/")
        Anagrafica anagrafica);

    /**
     * 
     * @param cf
     * @param cognome
     * @param cellulare
     * @param nome
     * @param telefono
     * @param email
     */
    @WebMethod
    @RequestWrapper(localName = "addUser", targetNamespace = "http://services/", className = "services.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://services/", className = "services.AddUserResponse")
    public void addUser(
        @WebParam(name = "nome", targetNamespace = "")
        String nome,
        @WebParam(name = "cognome", targetNamespace = "")
        String cognome,
        @WebParam(name = "cf", targetNamespace = "")
        String cf,
        @WebParam(name = "telefono", targetNamespace = "")
        String telefono,
        @WebParam(name = "cellulare", targetNamespace = "")
        String cellulare,
        @WebParam(name = "email", targetNamespace = "")
        String email);

    /**
     * 
     * @return
     *     returns java.util.List<services.Anagrafica>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listUsers", targetNamespace = "http://services/", className = "services.ListUsers")
    @ResponseWrapper(localName = "listUsersResponse", targetNamespace = "http://services/", className = "services.ListUsersResponse")
    public List<Anagrafica> listUsers();

}
